<?xml version="1.0"?>
<!--
  DashGo D1 ç®€åŒ–URDFæ¨¡åž‹ - ç”¨äºŽSim2Realæµ‹è¯•

  åˆ›å»ºæ—¶é—´: 2026-01-28 23:10:00
  åŸºäºŽ: dashgo_config.pyå‚æ•°å¯¹é½

  æœºå™¨äººå‚æ•°:
  - è½®è·: 0.3420 m
  - è½®å¾„: 0.1264 m (åŠå¾„: 0.0632 m)
  - ä½“åž‹: ç®€åŒ–åœ†å½¢åº•ç›˜

  åæ ‡ç³»:
  - base_link: æœºå™¨äººä¸­å¿ƒ
  - odom: é‡Œç¨‹è®¡åæ ‡ç³»
  - laser_link: é›·è¾¾åæ ‡ç³»ï¼ˆå‰ä¸Šæ–¹ï¼‰
-->
<robot name="dashgo_d1" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- =========================================================
       æœºå™¨äººå‚æ•°å®šä¹‰
    ========================================================== -->
  <xacro:property name="wheel_radius" value="0.0632"/>  <!-- è½®å­åŠå¾„ (m) -->
  <xacro:property name="wheel_length" value="0.04"/>     <!-- è½®å­å®½åº¦ (m) -->
  <xacro:property name="wheel_base" value="0.3420"/>     <!-- è½®è· (m) -->

  <xacro:property name="base_radius" value="0.20"/>       <!-- åº•ç›˜åŠå¾„ (m) -->
  <xacro:property name="base_height" value="0.15"/>       <!-- åº•ç›˜é«˜åº¦ (m) -->
  <xacro:property name="base_mass" value="5.0"/>          <!-- åº•ç›˜è´¨é‡ (kg) -->

  <xacro:property name="laser_radius" value="0.05"/>      <!-- é›·è¾¾åŠå¾„ (m) -->
  <xacro:property name="laser_height" value="0.10"/>      <!-- é›·è¾¾é«˜åº¦ (m) -->
  <xacro:property name="laser_mass" value="0.2"/>         <!-- é›·è¾¾è´¨é‡ (kg) -->

  <!-- é›·è¾¾å®‰è£…ä½ç½® -->
  <xacro:property name="laser_x" value="0.10"/>           <!-- å‰æ–¹è·ç¦» (m) -->
  <xacro:property name="laser_y" value="0.0"/>            <!-- å·¦å³åç§» (m) -->
  <xacro:property name="laser_z" value="0.20"/>           <!-- é«˜åº¦ (m) -->

  <!-- ææ–™å±žæ€§ -->
  <xacro:property name="wheel_mass" value="0.2"/>         <!-- å•ä¸ªè½®å­è´¨é‡ (kg) -->

  <!-- =========================================================
       åŸºç¡€é“¾æŽ¥ï¼ˆbase_linkï¼‰
    ========================================================== -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="blue">
        <color rgba="0.0 0.0 1.0 1.0"/>
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.10" radius="0.10"/>  <!-- æŠ¬é«˜5cmé¿å…æ‹–åº•ï¼ŒåŽšåº¦å‡åŠï¼ŒåŠå¾„ä¿æŒ0.10é¿å…æ°´å¹³ç¢°æ’ž -->
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>  <!-- ðŸ”¥ ä¿®å¤ï¼šé‡å¿ƒè·Ÿéšç¢°æ’žä½“ -->
      <mass value="${base_mass}"/>
      <inertia ixx="0.05" ixy="0" ixz="0" iyy="0.05" iyz="0" izz="0.08"/>
    </inertial>
  </link>

  <!-- =========================================================
       ä¸‡å‘è½®å®šä¹‰ï¼ˆCaster Wheelsï¼‰- Dashgo D1å®žæœºå‚æ•°
       å¸ƒå±€ï¼š1+2+1ï¼ˆå‰ä¸‡å‘ + ä¸­é©±åŠ¨ + åŽä¸‡å‘ï¼‰
    ========================================================== -->
  <xacro:property name="caster_radius" value="0.0127"/>   <!-- 1å¯¸ä¸‡å‘è½®åŠå¾„=12.7mm -->
  <xacro:property name="caster_mass" value="0.1"/>           <!-- ä¸‡å‘è½®è´¨é‡ -->

  <!-- å‰ä¸‡å‘è½® -->
  <link name="front_caster_link">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
      <mass value="${caster_mass}"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="front_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_caster_link"/>
    <!-- å‰ä¸‡å‘è½®ä½ç½®ï¼šåº•ç›˜å‰æ–¹ï¼ˆå‡è®¾1+2+1å¸ƒå±€ï¼Œå‰åŽå¯¹ç§°ï¼‰ -->
    <origin xyz="0.15 0 -0.05" rpy="0 0 0"/>
  </joint>

  <!-- åŽä¸‡å‘è½® -->
  <link name="rear_caster_link">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
      <mass value="${caster_mass}"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="rear_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="rear_caster_link"/>
    <!-- åŽä¸‡å‘è½®ä½ç½®ï¼šåº•ç›˜åŽæ–¹ -->
    <origin xyz="-0.15 0 -0.05" rpy="0 0 0"/>
  </joint>

  <!-- =========================================================
       é©±åŠ¨è½®å®šä¹‰
    ========================================================== -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_wheel_link">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
        <material name="black">
          <color rgba="0.0 0.0 0.0 1.0"/>
        </material>
      </visual>

      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      </collision>

      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
    </link>

    <!-- è½®å­å…³èŠ‚ -->
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="0 ${y_reflect * wheel_base/2} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- å·¦å³è½®å­ -->
  <xacro:wheel prefix="left" x_reflect="1" y_reflect="1"/>
  <xacro:wheel prefix="right" x_reflect="1" y_reflect="-1"/>

  <!-- =========================================================
       é›·è¾¾é“¾æŽ¥
    ========================================================== -->
  <link name="laser_link">
    <visual>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="red">
        <color rgba="1.0 0.0 0.0 1.0"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
      <mass value="${laser_mass}"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>

  <!-- é›·è¾¾å…³èŠ‚ -->
  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_link"/>
    <origin xyz="${laser_x} ${laser_y} ${laser_z}" rpy="0 0 0"/>
  </joint>

  <!-- =========================================================
       Gazeboä»¿çœŸæ’ä»¶ï¼ˆä¿®å¤TFå’ŒæŽ§åˆ¶ï¼‰
    ========================================================== -->

  <!-- å·®é€Ÿé©±åŠ¨æŽ§åˆ¶å™¨ï¼ˆå…³é”®ï¼ä¿®å¤odomâ†’base_link TFï¼‰ -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <updateRate>50</updateRate>
      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <wheelSeparation>${wheel_base}</wheelSeparation>
      <wheelDiameter>${2 * wheel_radius}</wheelDiameter>
      <wheelAcceleration>1.0</wheelAcceleration>
      <wheelTorque>20</wheelTorque>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_link</robotBaseFrame>
      <odometrySource>world</odometrySource>
      <publishWheelTF>true</publishWheelTF>
      <publishOdomTF>true</publishOdomTF>
      <publishWheelJointState>true</publishWheelJointState>
      <covariance_x>0.0001</covariance_x>
      <covariance_y>0.0001</covariance_y>
      <covariance_yaw>0.01</covariance_yaw>
    </plugin>
  </gazebo>

  <!-- é›·è¾¾ä¼ æ„Ÿå™¨æ’ä»¶ï¼ˆå‘å¸ƒ/scanæ•°æ®ï¼‰ -->
  <gazebo reference="laser_link">
    <sensor type="ray" name="laser_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>12.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="laser_controller" filename="libgazebo_ros_laser.so">
        <topicName>/scan</topicName>
        <frameName>laser_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- è½®å­æ‘©æ“¦åŠ›å±žæ€§ï¼ˆé˜²æ­¢æ‰“æ»‘å’Œç©¿æ¨¡ï¼‰ -->
  <gazebo reference="left_wheel_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="right_wheel_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
    <material>Gazebo/Black</material>
  </gazebo>

  <!-- ä¸‡å‘è½®æ‘©æ“¦åŠ›å±žæ€§ï¼ˆä½Žæ‘©æ“¦ï¼Œä¾¿äºŽè½¬å‘ï¼‰ -->
  <gazebo reference="front_caster_link">
    <mu1>0.0</mu1>  <!-- ä¸‡å‘è½®ä½Žæ‘©æ“¦ -->
    <mu2>0.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="rear_caster_link">
    <mu1>0.0</mu1>  <!-- ä¸‡å‘è½®ä½Žæ‘©æ“¦ -->
    <mu2>0.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
    <material>Gazebo/Grey</material>
  </gazebo>

</robot>
