<?xml version="1.0"?>
<!--
  DashGo D1 简化URDF模型 - 用于Sim2Real测试

  创建时间: 2026-01-28 23:10:00
  基于: dashgo_config.py参数对齐

  机器人参数:
  - 轮距: 0.3420 m
  - 轮径: 0.1264 m (半径: 0.0632 m)
  - 体型: 简化圆形底盘

  坐标系:
  - base_link: 机器人中心
  - odom: 里程计坐标系
  - laser_link: 雷达坐标系（前上方）
-->
<robot name="dashgo_d1" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- =========================================================
       机器人参数定义
    ========================================================== -->
  <xacro:property name="wheel_radius" value="0.0632"/>  <!-- 轮子半径 (m) -->
  <xacro:property name="wheel_length" value="0.04"/>     <!-- 轮子宽度 (m) -->
  <xacro:property name="wheel_base" value="0.3420"/>     <!-- 轮距 (m) -->

  <xacro:property name="base_radius" value="0.20"/>       <!-- 底盘半径 (m) -->
  <xacro:property name="base_height" value="0.15"/>       <!-- 底盘高度 (m) -->
  <xacro:property name="base_mass" value="5.0"/>          <!-- 底盘质量 (kg) -->

  <xacro:property name="laser_radius" value="0.05"/>      <!-- 雷达半径 (m) -->
  <xacro:property name="laser_height" value="0.10"/>      <!-- 雷达高度 (m) -->
  <xacro:property name="laser_mass" value="0.2"/>         <!-- 雷达质量 (kg) -->

  <!-- 雷达安装位置 -->
  <xacro:property name="laser_x" value="0.10"/>           <!-- 前方距离 (m) -->
  <xacro:property name="laser_y" value="0.0"/>            <!-- 左右偏移 (m) -->
  <xacro:property name="laser_z" value="0.20"/>           <!-- 高度 (m) -->

  <!-- 材料属性 -->
  <xacro:property name="wheel_mass" value="0.2"/>         <!-- 单个轮子质量 (kg) -->

  <!-- =========================================================
       基础链接（base_link）
    ========================================================== -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="blue">
        <color rgba="0.0 0.0 1.0 1.0"/>
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.10" radius="0.10"/>  <!-- 抬高5cm避免拖底，厚度减半，半径保持0.10避免水平碰撞 -->
      </geometry>
    </collision>

    <inertial>
      <mass value="${base_mass}"/>
      <inertia ixx="0.05" ixy="0" ixz="0" iyy="0.05" iyz="0" izz="0.08"/>
    </inertial>
  </link>

  <!-- =========================================================
       轮子定义
    ========================================================== -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_wheel_link">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
        <material name="black">
          <color rgba="0.0 0.0 0.0 1.0"/>
        </material>
      </visual>

      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      </collision>

      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
    </link>

    <!-- 轮子关节 -->
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="0 ${y_reflect * wheel_base/2} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- 左右轮子 -->
  <xacro:wheel prefix="left" x_reflect="1" y_reflect="1"/>
  <xacro:wheel prefix="right" x_reflect="1" y_reflect="-1"/>

  <!-- =========================================================
       雷达链接
    ========================================================== -->
  <link name="laser_link">
    <visual>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="red">
        <color rgba="1.0 0.0 0.0 1.0"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
      <mass value="${laser_mass}"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>

  <!-- 雷达关节 -->
  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_link"/>
    <origin xyz="${laser_x} ${laser_y} ${laser_z}" rpy="0 0 0"/>
  </joint>

  <!-- =========================================================
       Gazebo仿真插件（修复TF和控制）
    ========================================================== -->

  <!-- 差速驱动控制器（关键！修复odom→base_link TF） -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <updateRate>50</updateRate>
      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <wheelSeparation>${wheel_base}</wheelSeparation>
      <wheelDiameter>${2 * wheel_radius}</wheelDiameter>
      <wheelAcceleration>1.0</wheelAcceleration>
      <wheelTorque>20</wheelTorque>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_link</robotBaseFrame>
      <odometrySource>world</odometrySource>
      <publishWheelTF>true</publishWheelTF>
      <publishOdomTF>true</publishOdomTF>
      <publishWheelJointState>true</publishWheelJointState>
      <covariance_x>0.0001</covariance_x>
      <covariance_y>0.0001</covariance_y>
      <covariance_yaw>0.01</covariance_yaw>
    </plugin>
  </gazebo>

  <!-- 雷达传感器插件（发布/scan数据） -->
  <gazebo reference="laser_link">
    <sensor type="ray" name="laser_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>12.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="laser_controller" filename="libgazebo_ros_laser.so">
        <topicName>/scan</topicName>
        <frameName>laser_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- 轮子摩擦力属性（防止打滑和穿模） -->
  <gazebo reference="left_wheel_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="right_wheel_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
    <material>Gazebo/Black</material>
  </gazebo>

</robot>
