lakibeam_scan_node:
  ros__parameters:
    frame_id: laser
    output_topic: /scan
    inverted: false
    hostip: 0.0.0.0
    sensorip: 192.168.8.2
    port: 2368
    angle_offset: 0
    scanfreq: 30
    filter: 3
    laser_enable: true
    scan_range_start: 90
    scan_range_stop: 270
